python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_1 --b_dir images/tgt_sequential-56/1 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_2 --b_dir images/tgt_sequential-56/2 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_3 --b_dir images/tgt_sequential-56/3 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_4 --b_dir images/tgt_sequential-56/4 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_5 --b_dir images/tgt_sequential-56/5 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_6 --b_dir images/tgt_sequential-56/6 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_7 --b_dir images/tgt_sequential-56/7 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_8 --b_dir images/tgt_sequential-56/8 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_9 --b_dir images/tgt_sequential-56/9 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_10 --b_dir images/tgt_sequential-56/10 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_11 --b_dir images/tgt_sequential-56/11 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_12 --b_dir images/tgt_sequential-56/12 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_13 --b_dir images/tgt_sequential-56/13 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_14 --b_dir images/tgt_sequential-56/14 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_15 --b_dir images/tgt_sequential-56/15 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_16 --b_dir images/tgt_sequential-56/16 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_17 --b_dir images/tgt_sequential-56/17 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_18 --b_dir images/tgt_sequential-56/18 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_19 --b_dir images/tgt_sequential-56/19 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_20 --b_dir images/tgt_sequential-56/20 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_21 --b_dir images/tgt_sequential-56/21 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_22 --b_dir images/tgt_sequential-56/22 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_23 --b_dir images/tgt_sequential-56/23 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_24 --b_dir images/tgt_sequential-56/24 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_25 --b_dir images/tgt_sequential-56/25 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_26 --b_dir images/tgt_sequential-56/26 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_27 --b_dir images/tgt_sequential-56/27 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_28 --b_dir images/tgt_sequential-56/28 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_29 --b_dir images/tgt_sequential-56/29 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_30 --b_dir images/tgt_sequential-56/30 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_31 --b_dir images/tgt_sequential-56/31 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_32 --b_dir images/tgt_sequential-56/32 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_33 --b_dir images/tgt_sequential-56/33 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_34 --b_dir images/tgt_sequential-56/34 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_35 --b_dir images/tgt_sequential-56/35 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_36 --b_dir images/tgt_sequential-56/36 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_37 --b_dir images/tgt_sequential-56/37 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_38 --b_dir images/tgt_sequential-56/38 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_39 --b_dir images/tgt_sequential-56/39 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_40 --b_dir images/tgt_sequential-56/40 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_41 --b_dir images/tgt_sequential-56/41 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_42 --b_dir images/tgt_sequential-56/42 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_43 --b_dir images/tgt_sequential-56/43 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_44 --b_dir images/tgt_sequential-56/44 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_45 --b_dir images/tgt_sequential-56/45 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_46 --b_dir images/tgt_sequential-56/46 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_47 --b_dir images/tgt_sequential-56/47 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_48 --b_dir images/tgt_sequential-56/48 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_49 --b_dir images/tgt_sequential-56/49 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_50 --b_dir images/tgt_sequential-56/50 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_51 --b_dir images/tgt_sequential-56/51 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_52 --b_dir images/tgt_sequential-56/52 --operation combine
python get_data/combine-images.py --input_dir images/src_sequential/images --output_dir images/combine_230106/1_53 --b_dir images/tgt_sequential-56/53 --operation combine
